#!/bin/bash
# Quick Setup Guide for GitHub Actions

echo "=================================================="
echo "GitHub Actions Setup for NICDDF Automation"
echo "=================================================="
echo ""
echo "📋 STEP 1: Add GitHub Secrets"
echo "=================================================="
echo "Go to: Repository → Settings → Secrets and variables → Actions"
echo ""
echo "Add these secrets:"
echo ""
echo "REQUIRED:"
echo "  • NICDDF_USERNAME"
echo "  • NICDDF_PASSWORD"
echo ""
echo "OPTIONAL (WhatsApp Notifications):"
echo "  • WHATSAPP_ENABLED=true"
echo "  • WHATSAPP_TO=+447587821393"
echo "  • WHATSAPP_CALLMEBOT_URL=https://api.callmebot.com"
echo "  • WHATSAPP_CALLMEBOT_API_KEY=your_key"
echo ""
echo "OPTIONAL (Slack Notifications):"
echo "  • SLACK_WEBHOOK_URL=your_webhook_url"
echo ""
echo "OPTIONAL (Telegram Notifications):"
echo "  • TELEGRAM_ENABLED=true"
echo "  • TELEGRAM_BOT_TOKEN=your_token"
echo "  • TELEGRAM_CHAT_ID=your_chat_id"
echo ""
echo "=================================================="
echo "📅 STEP 2: Verify Workflow File"
echo "=================================================="
echo "✓ File location: .github/workflows/nicddf-automation.yml"
echo "✓ Commit and push this file to main branch"
echo ""
echo "=================================================="
echo "🚀 STEP 3: Run Tests"
echo "=================================================="
echo "Option 1 - Automatic Daily Run:"
echo "  • Runs at 9:00 AM UTC every day"
echo "  • No manual action needed"
echo ""
echo "Option 2 - Manual Trigger:"
echo "  • Go to: Actions → NICDDF Automation Tests"
echo "  • Click: Run workflow"
echo ""
echo "Option 3 - On Push:"
echo "  • Runs when pushing changes to main branch"
echo ""
echo "=================================================="
echo "📊 STEP 4: Monitor Results"
echo "=================================================="
echo "• Navigate to: Actions tab"
echo "• Click on workflow run to see details"
echo "• Download artifacts (report, results)"
echo "• Check Slack/WhatsApp for notifications"
echo ""
echo "=================================================="
echo "✅ Setup Complete!"
echo "=================================================="
echo ""
echo "For detailed setup: See GITHUB-ACTIONS-SETUP.md"
